name: Deploy to Production
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-production:
    name: Deploy production
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      enable-sentry: true
      docker-image: ghcr.io/AplinkosMinisterija/biip-maps-web
      build-args: |
        NODE_ENV=production
        VUE_APP_SENTRY_DSN=https://6bb481def89a4a3f842b278c693f0c21@sentry.biip.lt/13
        VUE_APP_SMALSUOLIS_API_HOST=https://smalsuolis.lt/api
        VUE_APP_QGIS_SERVER=https://gis.biip.lt
