name: Deploy to Development

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy-development:
    name: Deploy development
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Development
      enable-sentry: true
      docker-image: ghcr.io/AplinkosMinisterija/biip-maps-web
      build-args: |
        NODE_ENV=development
        VUE_APP_SENTRY_DSN=https://6bb481def89a4a3f842b278c693f0c21@sentry.biip.lt/13
        VUE_APP_SMALSUOLIS_API_HOST=https://dev.smalsuolis.lt/api
        VUE_APP_QGIS_SERVER=https://dev-gis.biip.lt
        VUE_APP_CDN_HOST=https://dev-cdn.biip.lt
